# Generated by Django 6.0.1 on 2026-01-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FilmModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swapiFilm_id", models.IntegerField(unique=True)),
                ("film_title", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
            ],
        ),
    ]
